### ISSUE TITLE
Nothing is displayed in the frame bottom toolbar.

### ISSUE THREAD

**Issue by leesunghyun** [CreativeSDK/android-getting-started-samples#29]
nothing is displayed in the frame bottom toolbar.
seems to fail to load items.
and crash app when click sticker bottom toolbar.
i want to set applicationIdSuffix of buildTypes in gradle setting.
#### Crash log.
```
 java.lang.NullPointerException: Attempt to invoke interface method 'int android.database.Cursor.getCount()' on a null object reference
                                                                                   at com.adobe.creativesdk.aviary.panels.StickersPanelAbstract.onLoadComplete(StickersPanelAbstract.java:190)
                                                                                   at com.adobe.creativesdk.aviary.panels.StickersPanelAbstract.onLoadComplete(StickersPanelAbstract.java:102)
                                                                                   at android.support.v4.content.Loader.deliverResult(Loader.java:126)
                                                                                   at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:105)
                                                                                   at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:37)
                                                                                   at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:249)
                                                                                   at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:77)
                                                                                   at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:476)
                                                                                   at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:493)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-10 10:58:32.302 880-2760/? W/ActivityManager:   Force finishing activity com.linecorp.linestickers.debug/com.adobe.creativesdk.aviary.AdobeImageEditorActivity
```

**Comment by leesunghyun** [comment]
sdk version
```
    compile 'com.adobe.creativesdk.foundation:auth:0.9.1186'
    compile 'com.adobe.creativesdk:image:4.6.3'
    compile 'com.localytics.android:library:3.8.0'
```

**Comment by ashryanbeats** [comment]
There was a compatibility issue with `auth:0.9.1186` and `image:4.6.3`.

We just released a new version of the Image Editor: `4.8.3`.

This repo has been updated to reflect that. Please try with the latest version of the repo and let us know if you continue to experience this issue.

**Comment by leesunghyun** [comment]
@ashryanbeats 
Thank you for the update. 
i checked this issue in 4.8.3.
but this issue continues to occur.
should not I set applicationIdSuffix to use adobe sdk?
