### ISSUE TITLE
java.lang.VerifyError: com/trello/rxlifecycle/components/support/RxAppCompatActivity

### ISSUE THREAD

**Issue by bbincybbaby** [CreativeSDK/android-getting-started-samples#33]
I am new to adobe creative SDK for android, I have integrated adobe creative SDK with my application successfully. Its running successfully on Android 5.0 and up. But when tried to run on 4.0, 4.1, 4.4, 4.4.2 and 4.4.4 it gives error like 

`FATAL EXCEPTION: main
                                                   Process: com.padath.imageprocessingaviary, PID: 13471
                                                   java.lang.VerifyError: com/trello/rxlifecycle/components/support/RxAppCompatActivity
                                                       at java.lang.Class.newInstanceImpl(Native Method)
                                                       at java.lang.Class.newInstance(Class.java:1208)
                                                       at android.app.Instrumentation.newActivity(Instrumentation.java:1067)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2296)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2470)
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:174)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1307)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:146)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5593)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
                                                       at dalvik.system.NativeStart.main(Native Method)`

	
i am also using a latest versions of both

**Comment by duwurensheng010** [comment]
I have this error too,  do you solve it and how.

**Comment by jiang111** [comment]
+1

**Comment by shubham-1996** [comment]
Any solutions?

**Comment by duwurensheng010** [comment]
I solve it bacause third party packet conflicts.

**Comment by bbincybbaby** [comment]
how ?

**Comment by Savan7002** [comment]
I also have the same issue, but I found that when I use any third party library it's lead to crashes, Please provide the solution if anybody have. Thanks in advance.

**Comment by Savan7002** [comment]
I am facing the same issue regarding Creative SDK, but I resolved same with the use of multidex. Please below steps for solving this error.

Enable Multidex and add gradel support to your app level gradel file
defaultConfig {
 multiDexEnabled true
}

dependencies {
compile 'com.android.support:multidex:1.0.1'
}
Now initialize Multidex at application level
@Override
public void onCreate() {
  MultiDex.install(this);
}
This solution works for me, I hope this will help you also.
