### ISSUE TITLE
Error while using support library version 26.0.0 or up

### ISSUE THREAD

**Issue by bharti-esense-4** [CreativeSDK/android-getting-started-samples#57]
I am getting error while using support library version **26.0.0**

AsyncTaskCompat class is deprecated in API level 26.0.0 Please refer [this](https://developer.android.com/reference/android/support/v4/os/AsyncTaskCompat.html) link for more information

` java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/os/AsyncTaskCompat;
                                                                         at com.adobe.creativesdk.aviary.AdobeImageEditorActivityAbstract.loadTools(AdobeImageEditorActivityAbstract.java:760)
                                                                         at com.adobe.creativesdk.aviary.AdobeImageEditorActivityAbstract.onPostCreate(AdobeImageEditorActivityAbstract.java:579)
                                                                         at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1221)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2641)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
                                                                         at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
                                                                      Caused by: java.lang.ClassNotFoundException: Didn't find class `

**Comment by iamdangerous** [comment]
See the solution [https://stackoverflow.com/questions/47887296/how-can-i-fix-this-error-in-android-adobe-sdk-tool](url)

**Comment by pushpalroy** [comment]
@iamdangerous Can you please provide a resource for the solution? The above link is 404.

**Comment by iamdangerous** [comment]
@pushpalroy I have updated my comment above please check the url now. You just have to **add two** classes that are remove from support library version **26.0.0**

**Comment by pushpalroy** [comment]
Thanks @iamdangerous . That solution worked.
